### ISSUE TITLE
Let's connect

### ISSUE THREAD

**Issue by Rahullkumr** [Rahullkumr/The-Git-Gurus#2]
guys! come here, let's connect

@Arunava125
@subhajit033
@omzi
@nida242004

**Comment by subhajit033** [comment]
Yeah let's connect

**Comment by omzi** [comment]
Hi everyone 👋🏽. Great to be here.

**Comment by omzi** [comment]
How do we connect? Is there a private chat or something?

**Comment by Rahullkumr** [comment]
Let's me build an organisation.

**Comment by omzi** [comment]
I think an organisation is nice and all but we still need a place to chat and strategize how to make commits to get more points.

**Comment by subhajit033** [comment]
Telegram will be a great place, btw i have my own chatting app😅

**Comment by omzi** [comment]
Yes, Telegram! Let's stick with Telegram for now 😅.

**Comment by subhajit033** [comment]
https://t.me/+M93QsHcGAuJmMmI9
join fast guys

**Comment by Rahullkumr** [comment]
Yes, Telegram would be better

@nida242004 
I am not in support of Discord because it requires a hell lot of resources and my laptop starts to lag.

**Comment by subhajit033** [comment]
@Rahullkumr 
@nida242004 
join telegram , link already given

**Comment by Rahullkumr** [comment]
wait a minute
